FROM golang:1.26 AS build
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o cliente_passageiro ./cmd/cliente_passageiro

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/cliente_passageiro .
ENTRYPOINT ["./cliente_passageiro"]
