FROM golang:1.26 AS build
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o servidor ./cmd/servidor

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/servidor .
EXPOSE 8080
ENTRYPOINT ["./servidor"]
