FROM golang:1.26 AS build
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o cliente_motorista ./cmd/cliente_motorista

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/cliente_motorista .
ENTRYPOINT ["./cliente_motorista"]
